### ISSUE TITLE
Print PDF button doesn't do anything

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-gallery#109]
"Print" page, Print PDF button doesn't do anything (exceptions are seen in the debugger)

**Comment by chiaramooney** [comment]
@tritao Can you investigate this? Maybe we need to add more to the example to display the results of hitting print?

**Comment by tritao** [comment]
Will check, I am guessing it's a 0.64 issue.

**Comment by jaimecbernardo** [comment]
I've looked into this.

The change in thread affinity for 0.64 means some of the code needs to be fixed in the module in order to run in the UI thread. I'll submit a PR to the module with the fix.

The `RNPrintCanvas` element needed was also removed from this repo:
https://github.com/microsoft/react-native-gallery/commit/6186a542740fbafab204c63c0db508f78865d6d3#diff-c18425ce68a25362f1ee0c2a974ff8d07dfa845bba65614a369766f5c110f100

Once I get the fix into `react-native-print` upstream I'll open a PR here to update the reference and re-add the `RNPrintCanvas`.

**Comment by jaimecbernardo** [comment]
I've submitted the fix to `react-native-print`: https://github.com/christopherdro/react-native-print/pull/134

**Comment by jaimecbernardo** [comment]
@asklar @chiaramooney 
Would you like a fix that references the react-native-print PR, or would you rather wait for it to be merged?

**Comment by asklar** [comment]
thanks a lot @jaimecbernardo! I tagged the print repo owner, let's see if they respond soon and we can just use their new package

**Comment by asklar** [comment]
@jaimecbernardo looks like 0.8.0 is released with your fix so it should be possible to upgrade gallery to use it : )

**Comment by jaimecbernardo** [comment]
Thank you for the heads-up.
I'll open a PR :)

**Comment by jaimecbernardo** [comment]
I've submitted the fix here: https://github.com/microsoft/react-native-gallery/pull/138
