### ISSUE TITLE
SketchCanvas Renders Gallery Blank in Release Mode

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-gallery#139]
SketchCanvas leaves Gallery blank in Release mode following #127. @jaimecbernardo could you look into this?

**Comment by jaimecbernardo** [comment]
I'll give it a try.

**Comment by jaimecbernardo** [comment]
Hi @chiaramooney, it works in release for me.

It's possible that you're getting the previous version of react-native-sketch-canvas. To avoid this, it's best to run `yarn cache clean` as instructed in those PR instructions: https://github.com/microsoft/react-native-gallery/pull/127#issue-623797935

I'll open a PR to add a specific commit in `package.json` to see if that doesn't have this yarn cache issue. There's been a bug fix on the module since it was last updated here, so this will update it as well.

**Comment by jaimecbernardo** [comment]
Hi. I've opened a PR that might help with this issue here: https://github.com/microsoft/react-native-gallery/pull/140

**Comment by chiaramooney** [comment]
Ok got it to work! Will look at the new PR now.
