### ISSUE TITLE
Can't see the menu/drawer after running the app

### ISSUE THREAD

**Issue by tlenclos** [microsoft/react-native-gallery#148]
Can't navigate through examples since menu is not visible 

![image](https://user-images.githubusercontent.com/686101/121961453-be1f9b00-cd67-11eb-80f5-127d6adb520c.png)

**Comment by chrisglein** [comment]
Possibly and issue with theming. When web debugging is enabled the theme APIs don't work correctly and always use light theme. Workarounds:
- Use light theme
- Use direct debugging
- Run in release

All that said, this will be fixed in future versions of RNW just as a result of transitioning off of web debugging.

Pretty bad experience to have the main menu button not show in the reasonable config of debug+web debugging.

RNW could fork the theming code to workaround this in the meantime maybe?

**Comment by chiaramooney** [comment]
Connected to #17 closing now.
