### ISSUE TITLE
Win11 dark mode, and switching RN Gallery to light mode causes some rendering issues

### ISSUE THREAD

**Issue by dannyvv** [microsoft/react-native-gallery#187]
## Shared steps
###Repro:
1. On win 21H2, with dark mode as default
2. Launch RN Gallery app
3. Click hamburger
4. CLick settings
5. Select light theme

### Repro
6. Click hambuger
### Result
White on white menu, even no scrollbar
![image](https://user-images.githubusercontent.com/11037542/151421296-5195c1af-8d12-4b17-b902-dbc8c4929a3a.png)

### Repro
6. Go to settings
### Result
On the settings page, notice the theme dropdown has no borders indicating it is a dropdown...
![image](https://user-images.githubusercontent.com/11037542/151421809-a1fb1882-9c0b-40ef-b616-8e1f8eacd47c.png)
### Repro (cont)
7. Hover over the dropdown
### Result
Notice that now the text 'light' is white on white:
![image](https://user-images.githubusercontent.com/11037542/151422175-a164c2fa-eedc-4757-93e4-07ab68d38747.png)

### Repro (cont)
8. Click on the theme dropdown
### Result
Notice that the dropdown still renders using dark theme:
![image](https://user-images.githubusercontent.com/11037542/151421971-20ac0207-7fa4-4c20-9125-5b6b1858f387.png)

**Comment by chrisglein** [comment]
I had thought that the in-app toggle for light/dark mode was supposed to only toggle the control samples, not the whole app. But it's certainly changing much of the app, and inconsistently. As is, using this feature makes the app unusable.

**Comment by chiaramooney** [comment]
Filing a PR soon to fix first issue of blank menu. 

Issue two is an RNW limitation. Unfortunately, we are unable to toggle native theme at runtime (attempting to do so crashes the app given the way RNW theme has been set up). So changing the toggle to light theme does not change the native elements to light theme hence why the border appears missing because the app background has switched to light theme but the picker has stayed in dark theme. 

Originally theme toggle was just code snippets but we started the work to toggle the entire app, so that we could support opening the app in light theme and dark theme. But given the issue 2 limitation we can't support the mismatch. I'll have a PR out soon to disable the toggle for now, so people don't walk themselves into the weird state.
