### ISSUE TITLE
Page Badges aren't easy to see to read in dark mode (nor do they look exactly right in light mode)

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-gallery#381]
The badges in the corners of the pages don't always match the theme of the app in a way that's readable.

![image](https://github.com/microsoft/react-native-gallery/assets/10852185/6edee93b-f800-43f5-b397-06379fdbb9b8)

![image](https://github.com/microsoft/react-native-gallery/assets/10852185/5f017042-c685-492d-9008-3fba6711dde3)

**Comment by Yajur-Grover** [comment]
I've changed the color of the Native Control Badge so that it is distinguishable from the background in light mode. However, I can't seem to test the change in Dark Mode as this is what Gallery looks like for me in Dark Mode: 
![image](https://github.com/microsoft/react-native-gallery/assets/157416350/4fdc9d41-0c98-43c4-b694-aadb654ade1e)

I've tried changing the settings and then cleaning/rebuilding the rngallery solution, as well as rebooting my machine but nothing seems to be working.

**Comment by chrisglein** [comment]
Reminder: Check with contrast analyzer tool with Accessibliity Insights as part of this.

**Comment by chrisglein** [comment]
> Reminder: Check with contrast analyzer tool with Accessibliity Insights as part of this.

@Yajur-Grover FYI

### Light mode
✅
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/13cad10d-dccc-4aa4-a3e5-846f6258e98e)
✅
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/c273a374-9d6d-400d-be04-97f43f87c0d5)

### Dark mode
✅
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/1e9e9319-6001-45a8-8b2e-b2be7c1e84a3)
❌
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/4550467c-91e2-4674-9bc2-84c90873597c)

This implies that the dark mode community module button (white on accent color) needs to be fixed for dark mode.
Which I believe means moving to "TextOnAccentFillColorPrimaryBrush":
![image](https://github.com/microsoft/react-native-gallery/assets/26607885/fb80714d-b6dc-4ff5-a6e5-a6502d6724c5)
